{{- if eq .Values.certs.mode "custom" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hami-dra-webhook.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{- .Values.certs.custom.crt | b64enc | indent 4 }}
  tls.key: |
    {{- .Values.certs.custom.key | b64enc | indent 4 }}
{{- end }}
