apiVersion: v1
kind: Service
metadata:
  name: {{ include "hami.dra.webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hami-dra-webhook.selectorLabels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  selector:
    {{- include "hami-dra-webhook.selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      targetPort: 8443
      name: webhook
