apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dra-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-dra-webhook
    {{- include "hami-dra-webhook.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hami-dra-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hami-dra-webhook.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-dra-webhook-serviceaccount
      containers:
        - name: webhook
          image: {{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}
          imagePullPolicy: "IfNotPresent"
          command:
            - /webhook
            - --v=5
            - --bind-address=0.0.0.0
            - --secure-port=8443
            - --cert-dir=/tls
            - --tls-cert-file-name=tls.crt
            - --tls-private-key-file-name=tls.key
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8000
            - --device-config-file=/device-config.yaml
          ports:
            - containerPort: 8443
              name: webhook
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8000
              name: health
              protocol: TCP
          volumeMounts:
            - name: device-config
              mountPath: /device-config.yaml
              subPath: device-config.yaml
            - name: tls-config
              mountPath: /tls
              readOnly: true
          # readinessProbe:
          #   httpGet:
          #     path: /readyz
          #     port: 8000
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /readyz
          #     port: 8000
          #     scheme: HTTP
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: device-config
          configMap:
            name: {{ .Release.Name }}-device-config
        - name: tls-config
          secret:
            secretName: {{ if .Values.certs.certManager.enabled }}{{ .Release.Name }}-dra-webhook-tls{{ else }}{{ .Release.Name }}-tls{{ end }}
