apiVersion: v2
name: hami-dra-webhook
description: A Helm chart for HAMi DRA Webhook - A Kubernetes webhook server template
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - webhook
  - kubernetes
  - admission-controller
  - hami
  - dra
home: https://github.com/Project-HAMi/HAMi-DRA
sources:
  - https://github.com/Project-HAMi/HAMi-DRA
maintainers:
  - name: The HAMi Authors

